# Generated by Django 3.2.4 on 2021-06-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20210619_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, max_length=250, on_delete=django.db.models.deletion.CASCADE, to='quest.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
